import ky from "ky-universal";
import { z } from "zod";

import { createTRPCRouter, publicProcedure } from "../trpc";

const schema = z.object({
  boards: z.array(
    z.union([
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        custom_spoilers: z.number(),
        is_archived: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        user_ids: z.number(),
        country_flags: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        user_ids: z.number(),
        is_archived: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
        code_tags: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
        webm_audio: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
        min_image_width: z.number(),
        min_image_height: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
        oekaki: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
        country_flags: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        custom_spoilers: z.number(),
        is_archived: z.number(),
        sjis_tags: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        custom_spoilers: z.number(),
        is_archived: z.number(),
        board_flags: z.object({
          "4CC": z.string(),
          ADA: z.string(),
          AN: z.string(),
          ANF: z.string(),
          APB: z.string(),
          AJ: z.string(),
          AB: z.string(),
          AU: z.string(),
          BB: z.string(),
          BM: z.string(),
          BP: z.string(),
          BS: z.string(),
          CL: z.string(),
          CO: z.string(),
          CG: z.string(),
          CHE: z.string(),
          CB: z.string(),
          DAY: z.string(),
          DD: z.string(),
          DER: z.string(),
          DT: z.string(),
          DIS: z.string(),
          EQA: z.string(),
          EQF: z.string(),
          EQP: z.string(),
          EQR: z.string(),
          EQT: z.string(),
          EQI: z.string(),
          EQS: z.string(),
          ERA: z.string(),
          FAU: z.string(),
          FLE: z.string(),
          FL: z.string(),
          GI: z.string(),
          HT: z.string(),
          IZ: z.string(),
          LI: z.string(),
          LT: z.string(),
          LY: z.string(),
          MA: z.string(),
          MAU: z.string(),
          MIN: z.string(),
          NI: z.string(),
          NUR: z.string(),
          OCT: z.string(),
          PAR: z.string(),
          PC: z.string(),
          PCE: z.string(),
          PI: z.string(),
          PLU: z.string(),
          PM: z.string(),
          PP: z.string(),
          QC: z.string(),
          RAR: z.string(),
          RD: z.string(),
          RLU: z.string(),
          S1L: z.string(),
          SCO: z.string(),
          SHI: z.string(),
          SIL: z.string(),
          SON: z.string(),
          SP: z.string(),
          SPI: z.string(),
          SS: z.string(),
          STA: z.string(),
          STL: z.string(),
          SPT: z.string(),
          SUN: z.string(),
          SUS: z.string(),
          SWB: z.string(),
          TFA: z.string(),
          TFO: z.string(),
          TFP: z.string(),
          TFS: z.string(),
          TFT: z.string(),
          TFV: z.string(),
          TP: z.string(),
          TS: z.string(),
          TWI: z.string(),
          TX: z.string(),
          VS: z.string(),
          ZE: z.string(),
          ZS: z.string(),
        }),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        custom_spoilers: z.number(),
        is_archived: z.number(),
        text_only: z.number(),
        require_subject: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        user_ids: z.number(),
        is_archived: z.number(),
        country_flags: z.number(),
        board_flags: z.object({
          AC: z.string(),
          AN: z.string(),
          BL: z.string(),
          CF: z.string(),
          CM: z.string(),
          CT: z.string(),
          DM: z.string(),
          EU: z.string(),
          FC: z.string(),
          GN: z.string(),
          GY: z.string(),
          JH: z.string(),
          KN: z.string(),
          MF: z.string(),
          NB: z.string(),
          NT: z.string(),
          NZ: z.string(),
          PC: z.string(),
          PR: z.string(),
          RE: z.string(),
          MZ: z.string(),
          TM: z.string(),
          TR: z.string(),
          UN: z.string(),
          WP: z.string(),
        }),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        user_ids: z.number(),
        is_archived: z.number(),
        require_subject: z.number(),
        oekaki: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        is_archived: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        is_archived: z.number(),
        math_tags: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        custom_spoilers: z.number(),
        is_archived: z.number(),
        require_subject: z.number(),
      }),
      z.object({
        board: z.string(),
        title: z.string(),
        ws_board: z.number(),
        per_page: z.number(),
        pages: z.number(),
        max_filesize: z.number(),
        max_webm_filesize: z.number(),
        max_comment_chars: z.number(),
        max_webm_duration: z.number(),
        bump_limit: z.number(),
        image_limit: z.number(),
        cooldowns: z.object({
          threads: z.number(),
          replies: z.number(),
          images: z.number(),
        }),
        meta_description: z.string(),
        spoilers: z.number(),
        is_archived: z.number(),
        sjis_tags: z.number(),
        oekaki: z.number(),
      }),
    ]),
  ),
});

export const boardsRouter = createTRPCRouter({
  getAllBoards: publicProcedure
    .output(schema)
    .query(async () => await ky.get("https://a.4cdn.org/boards.json").json()),
  getBoard: publicProcedure
    .input(z.string())
    .output(schema)
    .query(
      async ({ input }) =>
        await ky.get(`https://a.4cdn.org/${input}/theads.json`).json(),
    ),
});
